package com.hmvsoluciones.saas.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ClienteAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClienteAllPropertiesEquals(Cliente expected, Cliente actual) {
        assertClienteAutoGeneratedPropertiesEquals(expected, actual);
        assertClienteAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClienteAllUpdatablePropertiesEquals(Cliente expected, Cliente actual) {
        assertClienteUpdatableFieldsEquals(expected, actual);
        assertClienteUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClienteAutoGeneratedPropertiesEquals(Cliente expected, Cliente actual) {
        assertThat(actual)
            .as("Verify Cliente auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClienteUpdatableFieldsEquals(Cliente expected, Cliente actual) {
        assertThat(actual)
            .as("Verify Cliente relevant properties")
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getEmail()).as("check email").isEqualTo(expected.getEmail()))
            .satisfies(a -> assertThat(a.getTelefono()).as("check telefono").isEqualTo(expected.getTelefono()))
            .satisfies(a -> assertThat(a.getRazonSocial()).as("check razonSocial").isEqualTo(expected.getRazonSocial()))
            .satisfies(a -> assertThat(a.getRfc()).as("check rfc").isEqualTo(expected.getRfc()))
            .satisfies(a -> assertThat(a.getActivo()).as("check activo").isEqualTo(expected.getActivo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClienteUpdatableRelationshipsEquals(Cliente expected, Cliente actual) {
        // empty method
    }
}
